### ISSUE TITLE
Platform error device_tracker.experiaboxv10a - Integration 'experiaboxv10a' not found

### ISSUE THREAD

**Issue by Schaduwval** [mversluijs/homeassistant-experiabox-v10a#1]
Beste mversluijs, 

Ik ben in het bezit van een experiabox v10a, en zou dit graag werkend krijgen. Echter ik na het aanpassen van de YAML configuratie file de onderstaande foutmelding: 

`Platform error device_tracker.experiaboxv10a - Integration 'experiaboxv10a' not found.`

In de logs kom ik de volgende melding tegen: 

`2023-02-02 17:36:14.837 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'experiaboxv10' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
`

Wat ik ook probeer, niets lijkt te werken. Werkt de device tracker nog voor jou? 

Groeten.

**Comment by mversluijs** [comment]
Hey @Schaduwval,
Kun je mij de inhoud van jouw manifest.json eens laten zien? Daar zou als het goed is een version key "1.0.1" in moeten staan.

cheers

**Comment by Schaduwval** [comment]
Hey @mversluijs 
Ja dat klopt inderdaad, zie hieronder: 

`{
  "domain": "experiaboxv10a",
  "name": "experiaboxv10a",
  "documentation": "https://github.com/FrankZZ/homeassistant-experiabox-v10a",
  "version": "1.0.1",
  "requirements": [],
  "dependencies": [],
  "codeowners": [
      "@FrankZZ",
      "@kadima-tech"
  ]
}`

**Comment by WeterPeter** [comment]
Heeft iemand dit aan de praat gekregen?
Ik blijf maar krijgen : Platform error device_tracker.experiaboxv10a - Integration 'experiaboxv10a' not found.

Mijn manifest.json heb ik aangepast met de version regel :
{
    "domain": "experiaboxv10a",
    "name": "experiaboxv10a",
    "documentation": "https://github.com/FrankZZ/homeassistant-experiabox-v10a",
   "version": "1.0.1",
    "requirements": [],
    "dependencies": [],
    "codeowners": [
        "@FrankZZ",
        "@kadima-tech"
    ]
}

**Comment by mversluijs** [comment]
> Heeft iemand dit aan de praat gekregen? Ik blijf maar krijgen : Platform error device_tracker.experiaboxv10a - Integration 'experiaboxv10a' not found.
> 
> Mijn manifest.json heb ik aangepast met de version regel : { "domain": "experiaboxv10a", "name": "experiaboxv10a", "documentation": "https://github.com/FrankZZ/homeassistant-experiabox-v10a", "version": "1.0.1", "requirements": [], "dependencies": [], "codeowners": [ "@FrankZZ", "@kadima-tech" ] }

Hmm vreemd, bij mij werkt het wel.

Heb je onder custom_components een folder met experiaboxv10a met daarin alle bestanden?
![image](https://user-images.githubusercontent.com/101642361/221192002-ecb5f05e-7100-4c33-b18a-5d129f7a6dd5.png)

Heb je in je configuration.yaml een entry vergelijkbaar met onderstaande?
```
device_tracker:
  - platform: experiaboxv10a
    host: ip_adress_router
    username: !secret experiaboxv10_username
    password: !secret experiaboxv10_password
    interval_seconds: 90
    new_device_defaults:
      track_new_devices: True
```

**Comment by WeterPeter** [comment]
Ik moest de HASS docker zelf een reboot geven want HASS wilde dat niet door de foutmelding. Ook gelijk jouw config overgenomen. Nu heb ik geen foutmelding en ik zie de entiteiten als ik het goed heb. Nog even verder puzzelen maar ik ben een stap verder.

Dank je!

**Comment by Schaduwval** [comment]
> > Heeft iemand dit aan de praat gekregen? Ik blijf maar krijgen : Platform error device_tracker.experiaboxv10a - Integration 'experiaboxv10a' not found.
> > Mijn manifest.json heb ik aangepast met de version regel : { "domain": "experiaboxv10a", "name": "experiaboxv10a", "documentation": "https://github.com/FrankZZ/homeassistant-experiabox-v10a", "version": "1.0.1", "requirements": [], "dependencies": [], "codeowners": [ "@FrankZZ", "@kadima-tech" ] }
> 
> Hmm vreemd, bij mij werkt het wel.
> 
> Heb je onder custom_components een folder met experiaboxv10a met daarin alle bestanden? ![image](https://user-images.githubusercontent.com/101642361/221192002-ecb5f05e-7100-4c33-b18a-5d129f7a6dd5.png)
> 
> Heb je in je configuration.yaml een entry vergelijkbaar met onderstaande?
> 
> ```
> device_tracker:
>   - platform: experiaboxv10a
>     host: ip_adress_router
>     username: !secret experiaboxv10_username
>     password: !secret experiaboxv10_password
>     interval_seconds: 90
>     new_device_defaults:
>       track_new_devices: True
> ```

Nu met de bovenstaande gegevens werken de device trackers ook bij mij.

Bedankt voor je hulp! @mversluijs
